### ISSUE TITLE
Not starting on Win 10

### ISSUE THREAD

**Issue by FilatovDenys** [Synthetixio/synpress#135]
I cant run synpress on win 10.

**Comment by FilatovDenys** [comment]
**Message:** The plugins file is missing or invalid.

Your `pluginsFile` is set to `C:\Projects\111\node_modules\@synthetixio\synpress\plugins\index.js`, but either the file is missing, it contains a syntax error, or threw an error when required. The `pluginsFile` must be a `.js`, `.ts`, or `.coffee` file.

Or you might have renamed the extension of your `pluginsFile`. If that's the case, restart the test runner.

Please fix this, or set `pluginsFile` to `false` if a plugins file is not necessary for your project.

**Details:** C:\Projects\111\node_modules\@synthetixio\synpress\pages\metamask\page.js:3
export const pageElements = {
^^^^^^

SyntaxError: Unexpected token 'export'
    at wrapSafe (internal/modules/cjs/loader.js:986:16)
    at Module._compile (internal/modules/cjs/loader.js:1034:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1108:10)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12684)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (C:\Projects\111\node_modules\@synthetixio\synpress\commands\metamask.js:3:26)
    at Module._compile (internal/modules/cjs/loader.js:1078:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1108:10)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12684)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)

**Stack trace:**
```
Error: The plugins file is missing or invalid.

Your `pluginsFile` is set to `C:\Projects\111\node_modules\@synthetixio\synpress\plugins\index.js`, but either the file is missing, it contains a syntax error, or threw an error when required. The `pluginsFile` must be a `.js`, `.ts`, or `.coffee` file.

Or you might have renamed the extension of your `pluginsFile`. If that's the case, restart the test runner.

Please fix this, or set `pluginsFile` to `false` if a plugins file is not necessary for your project.
    at Object.get (C:\Users\Denis\AppData\Local\Cypress\Cache\7.0.1\Cypress\resources\app\packages\server\lib\errors.js:988:15)
    at EventEmitter.<anonymous> (C:\Users\Denis\AppData\Local\Cypress\Cache\7.0.1\Cypress\resources\app\packages\server\lib\plugins\index.js:154:21)
    at EventEmitter.emit (events.js:315:20)
    at ChildProcess.<anonymous> (C:\Users\Denis\AppData\Local\Cypress\Cache\7.0.1\Cypress\resources\app\packages\server\lib\plugins\util.js:19:22)
    at ChildProcess.emit (events.js:315:20)
    at emit (internal/child_process.js:903:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)

```

**Comment by drptbl** [comment]
@FilatovDenys what is the error? node and npm versions?

**Comment by FilatovDenys** [comment]
Hi! I install synpress by npm comand `npm install @synthetixio/synpress` after that try run synpress used comands from readme `synpress run` and `synpress open` and have this error 
`synpress : The term 'synpress' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is 
 correct and try again.
At line:1 char:1
+ synpress open
+ ~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (synpress:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException`

node version 14.15.5  npm version 6.14.11

**Comment by FilatovDenys** [comment]
Perhaps I am doing something wrong when installing? Can you give more detailed installation instructions step by step? Thank you for your time !

**Comment by ola-jha** [comment]
add `npx` before `synpess run`

**Comment by drptbl** [comment]
🙏
