### ISSUE TITLE
Metamask setup blocks on seed phrase

### ISSUE THREAD

**Issue by NameItNow** [Synthetixio/synpress#242]
Hey,

So I was just trying to launch a simple test with `synpress run`, the metamask extension opened in the test controlled browser but it just blocks on the wallet seed page. Synpress isn't typing my seed and I don't know why...

I checked my metamask version it's the latest 10.2.2 (so the latest).
Before running `synpress run` I call a bash script that sets my environment variables.

The script line in my package.json
`"test:cli": "./.secret.sh && synpress run",`

Below is my .secret.sh file that runs before tests and exports my env variables (obviously SECRET_WORDS and PRIVATE_KEY values have been changed here)
```
export SECRET_WORDS="word word..."
export PRIVATE_KEY=abcde1234
export NETWORK=localhost // by the way is it a problem if my metamask network is called hardhat 8545?
export RPC_URL=http://127.0.0.1:8545/
export CHAIN_ID=31337

// Just a simple check to be sure my env variables where set
echo $SECRET_WORDS
echo $PRIVATE_KEY
echo $NETWORK
echo $RPC_URL
echo $CHAIN_ID
```

Here is the output
```
====================================================================================================

  (Run Starting)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Cypress:    8.3.0                                                                              │
  │ Browser:    Chrome 94                                                                          │
  │ Specs:      1 found (connection-spec.js)                                                       │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


────────────────────────────────────────────────────────────────────────────────────────────────────
                                                                                                    
  Running:  connection-spec.js                                                              (1 of 1)


  1) "before all" hook for "An uncaught error was detected outside of a test"

  0 passing (34s)
  1 failing

  1) "before all" hook for "An uncaught error was detected outside of a test":
     CypressError: `cy.screenshot()` timed out waiting `30000ms` to complete.

Because this error occurred during a `before all` hook we are skipping all of the remaining tests.
      at http://localhost:3000/__cypress/runner/cypress_runner.js:145415:22
      at tryCatcher (http://localhost:3000/__cypress/runner/cypress_runner.js:13212:23)
      at http://localhost:3000/__cypress/runner/cypress_runner.js:8334:41
      at tryCatcher (http://localhost:3000/__cypress/runner/cypress_runner.js:13212:23)
      at Promise._settlePromiseFromHandler (http://localhost:3000/__cypress/runner/cypress_runner.js:11147:31)
      at Promise._settlePromise (http://localhost:3000/__cypress/runner/cypress_runner.js:11204:18)
      at Promise._settlePromise0 (http://localhost:3000/__cypress/runner/cypress_runner.js:11249:10)
      at Promise._settlePromises (http://localhost:3000/__cypress/runner/cypress_runner.js:11325:18)
      at _drainQueueStep (http://localhost:3000/__cypress/runner/cypress_runner.js:7919:12)
      at _drainQueue (http://localhost:3000/__cypress/runner/cypress_runner.js:7912:9)
      at Async.../../node_modules/bluebird/js/release/async.js.Async._drainQueues (http://localhost:3000/__cypress/runner/cypress_runner.js:7928:5)
      at Async.drainQueues (http://localhost:3000/__cypress/runner/cypress_runner.js:7798:14)



Warning: We failed processing this video.

This error will not alter the exit code.

TimeoutError: operation timed out
    at afterTimeout (/Users/vitch/Library/Caches/Cypress/8.3.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/timers.js:46:19)
    at Timeout.timeoutTimeout [as _onTimeout] (/Users/vitch/Library/Caches/Cypress/8.3.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/timers.js:76:13)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)


  (Results)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Tests:        1                                                                                │
  │ Passing:      0                                                                                │
  │ Failing:      1                                                                                │
  │ Pending:      0                                                                                │
  │ Skipped:      0                                                                                │
  │ Screenshots:  0                                                                                │
  │ Video:        false                                                                            │
  │ Duration:     34 seconds                                                                       │
  │ Spec Ran:     connection-spec.js                                                               │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


====================================================================================================

  (Run Finished)


       Spec                                              Tests  Passing  Failing  Pending  Skipped  
  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ ✖  connection-spec.js                       00:34        1        -        1        -        - │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
    ✖  1 of 1 failed (100%)                     00:34        1        -        1        -        -  

Cypress run results: 1 total tests, 0 passed, 1 failed
```

**Comment by NameItNow** [comment]
Hey, so in the end I just created a bash script called from within my package.json
```
SECRET_WORDS="word" NETWORK=localhost RPC_URL=http://127.0.0.1:8545/ CHAIN_ID=31337 synpress run
```
