### ISSUE TITLE
`cy.task('setupMetamask')` failed with the following error:  > Cannot read properties of undefined (reading 'waitForTimeout')

### ISSUE THREAD

**Issue by dev2021-ctrl** [Synthetixio/synpress#370]
My test script is below.the issue is random so sometimes the tests are passed and sometimes it fails.
I am running on ubuntu with latetst verion of synpress.
I can share the synpress json file fi needed.
Please advise anyone .A bit urgent.

describe('Metamask', () => {
  context('Test11 commands', () => {

    it(`Try to connect to website`, () => {
      cy.visit('/');
      cy.contains('Welcome')

    });

  });
});

Below are the error logs:

  1) "before all" hook for "Try to connect to website"

  0 passing (379ms)
  1 failing

  1) Metamask
       Test11 commands
         "before all" hook for "Try to connect to website":
     CypressError: `cy.task('setupMetamask')` failed with the following error:

> Cannot read properties of undefined (reading 'waitForTimeout')

https://on.cypress.io/api/task

Because this error occurred during a `before all` hook we are skipping all of the remaining tests.
      at http://localhost/__cypress/runner/cypress_runner.js:161147:78
      at tryCatcher (http://localhost/__cypress/runner/cypress_runner.js:13196:23)
      at Promise._settlePromiseFromHandler (http://localhost/__cypress/runner/cypress_runner.js:11131:31)
      at Promise._settlePromise (http://localhost/__cypress/runner/cypress_runner.js:11188:18)
      at Promise._settlePromise0 (http://localhost/__cypress/runner/cypress_runner.js:11233:10)
      at Promise._settlePromises (http://localhost/__cypress/runner/cypress_runner.js:11309:18)
      at _drainQueueStep (http://localhost/__cypress/runner/cypress_runner.js:7903:12)
      at _drainQueue (http://localhost/__cypress/runner/cypress_runner.js:7896:9)
      at Async.../../node_modules/bluebird/js/release/async.js.Async._drainQueues (http://localhost/__cypress/runner/cypress_runner.js:7912:5)
      at Async.drainQueues (http://localhost/__cypress/runner/cypress_runner.js:7782:14)
  
  From Node.js Internals:
    TypeError: Cannot read properties of undefined (reading 'waitForTimeout')
        at Object.initialSetup (/main/node_modules/@synthetixio/synpress/commands/metamask.js:557:37)
    at runMicrotasks (<anonymous>)
        at processTicksAndRejections (node:internal/process/task_queues:96:5)
        at setupMetamask (/main/node_modules/@synthetixio/synpress/plugins/index.js:211:7)

**Comment by saxenashivang** [comment]
You can check this - https://github.com/saxenashivang/cypress-metamask-v2, I have updated the code and solved the known issues.

**Comment by Eveelin** [comment]
I have the same issue, using "synpress open" command

**Comment by Christopher-Stevers** [comment]
I have the same issue as well, only when I use synpress open.

**Comment by quiet-node** [comment]
@drptbl Hello this seems to happen again

I use it in a support.js file
import '@synthetixio/synpress/support/index';

And I got this same error 
![image](https://github.com/user-attachments/assets/e224ec4b-e37a-44f5-957f-6b3ceab81f21)


Currently using latest synpress "@synthetixio/synpress": "^3.7.3",

**Comment by Mahmoud-Kandel** [comment]
> @drptbl Hello this seems to happen again
> 
> I use it in a support.js file import '@synthetixio/synpress/support/index';
> 
> And I got this same error ![image](https://private-user-images.githubusercontent.com/66233296/386356650-e224ec4b-e37a-44f5-957f-6b3ceab81f21.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzNDkyNDMsIm5iZiI6MTczMzM0ODk0MywicGF0aCI6Ii82NjIzMzI5Ni8zODYzNTY2NTAtZTIyNGVjNGItZTM3YS00NGY1LTk1N2YtNmIzY2VhYjgxZjIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA0VDIxNDkwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUyMmQyODQ1MzUyYjQ1NTVhYjRkZWU2NDMyMTNhYTYyMmQxZjRhNGZhZTU3ZDc4MDI3NDJkNDlkZGIzOGRmZmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.1JL4r3Hgb8JdvrtBq26IO4djBsmbf5ccOTiq5LUjnEE)
> 
> Currently using latest synpress "@synthetixio/synpress": "^3.7.3",

I use the same version of synpress and got the same error after the new release of google chrome. make sure to downgrade google chrome version. I will recommend you to use these chrome versions
   - For Mac: 126.0.6478.182
   - For Win: 130.0.6723.70
