### ISSUE TITLE
Plugins file error on run/open

### ISSUE THREAD

**Issue by kennetheversole** [Synthetixio/synpress#393]
I apologize for my naiveness, but whenever I run `yarn synpress run/open` I am getting the following error. Any advice would be fantastic. I have not done anything more than whatever is in the install instructions for my setup. 

```
yarn run v1.22.18
$ /[project]/node_modules/.bin/synpress run
Your pluginsFile is invalid: [project]/node_modules/@synthetixio/synpress/plugins/index.js

It threw an error when required, check the stack trace below:

Error: Cannot find module '[project]/node_modules/abi-decoder/node_modules/web3-utils/lib/index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (node:internal/modules/cjs/loader:353:19)
    at Function.Module._findPath (node:internal/modules/cjs/loader:566:18)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:27)
    at Function.Module._resolveFilename (/root/.cache/Cypress/9.5.3/Cypress/resources/app/packages/server/node_modules/tsconfig-paths/lib/register.js:75:40)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> ([project]/node_modules/abi-decoder/index.js:1:22)
    at Module._compile (node:internal/modules/cjs/loader:1099:14)
    at Module.m._compile (/root/.cache/Cypress/9.5.3/Cypress/resources/app/node_modules/ts-node/src/index.ts:536:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Object.require.extensions.<computed> [as .js] (/root/.cache/Cypress/9.5.3/Cypress/resources/app/node_modules/ts-node/src/index.ts:539:12)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
Failed to run Cypress
Could not find Cypress test run results
error Command failed with exit code 1.

```

**Comment by drptbl** [comment]
@kennetheversole can you try with node 16 and npm 8? 🙏

**Comment by kennetheversole** [comment]
@drptbl That seems to work, but now I am getting issue with the metamask setup

```
cypress_runner.js:194882 CypressError: Cypress detected that you returned a promise from a command while also invoking one or more cy commands in that promise.

The command that returned the promise was:

  > `cy.task()`

The cy command you invoked inside the promise was:

  > `cy.visit()`

Because Cypress commands are already promise-like, you don't need to wrap them or return your own promise.

Cypress will resolve your command with whatever the final Cypress command yields.

The reason this is an error instead of a warning is because Cypress internally queues commands serially whereas Promises execute as soon as they are invoked. Attempting to reconcile this would prevent Cypress from ever resolving.
    at $Cy.cy.<computed> [as visit] (http://localhost:3000/__cypress/runner/cypress_runner.js:173265:72)
From Your Spec Code:
    at Context.eval (http://localhost:3000/__cypress/tests?p=node_modules/@synthetixio/synpress/support/index.js:640:15)

**Comment by robsel118** [comment]
did you figure out what was triggering the last error?
